# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a3e1b623c78e2f87e81b38c2fa9bab552043745980aab07ee35a058c5ebb931970f44da76198b899ce07013fcb818ac26b3d21c36b03869f5888ad45ad9af94

test:
  secret_key_base: 38806da523aca53331ffe6bcc736532f33ad040092b38c82bc9d5fac477bc4e0b3676ba11e8fd7f0960d586a3f08adff6996b45937e08b9e839283b85e55eee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
